demo:
  external:
    service:
      # Флаг, отвечающий за возможность работать с внешним сервисом, реализущим DemoOpenApi( см. папку resources )
      enabled: false
      # Хост внешнего сервиса
      host: 26.141.131.233
      # Порт внешнего сервиса
      port: 8080