openapi: 3.0.3
info:
  title: Demo DataBase Api
  version: 1.0.0
tags:
  - name: main
paths:
  /student/select/all:
    get:
      tags:
        - main
      summary: Выборка из всех студентов
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      example: 1
                    name:
                      type: string
                      example: 'Иванов Иван'
                    age:
                      type: integer
                      format: int64
                      example: 25
                    nickname:
                      type: string
                      example: 'Погоняло'
                    description:
                      type: array
                      items:
                        type: string
                        example: 'какое-то описание'
  /student/add:
    post:
      tags:
        - main
      summary: Добавление студента
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Иванов Иван'
                age:
                  type: integer
                  format: int64
                  example: 10
                nickname:
                  type: string
                  example: 'Погоняло'
                description:
                  type: array
                  items:
                    type: string
                    example: 'какое-то описание'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: 'Студент успешно добален'
  /description/add:
    post:
      tags:
        - main
      summary: Добавление описания для студента по его id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
                description:
                  type: array
                  items:
                    type: string
                    example: 'какое-то описание'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: 'Описанние студенту успешно добавлено'
  /description/delete:
    post:
      tags:
        - main
      summary: Удаление описания по описанию и id студента
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  example: 1
                description:
                  type: array
                  items:
                    type: string
                    example: 'какое-то описание'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: 'Описанние успешно удалено'


