demo:
  external:
    service:
      # Флаг, отвечающий за возможность работать с внешним сервисом, реализущим DemoOpenApi( см. папку resources )
      enabled: false
      # Хост внешнего сервиса
      host: example.host
      # Порт внешнего сервиса
      port: example.port